namespace TsmServer.Domain.ValueObjects;

public record PlayerDataDto(
    int CharacterId,
    string Account,
    string Name,
    int Level,
    int Element,
    int Gender,
    int Hair,
    int HairColor,
    int SkinColor,
    int Hp,
    int MaxHp,
    int Sp,
    int MaxSp,
    int IntVal,
    int AtkVal,
    int DefVal,
    int HpaVal,
    int SpaVal,
    int AgiVal,
    int FreePoints,
    int SkillPoints,
    long Exp,
    long Gold,
    int MapId,
    int X,
    int Y,
    int GmLevel = 0,
    int PkMode = 0,
    int BagSlots = 25,
    int BankSlots = 25,
    int StorageSlots = 25
);
