<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\TsmClient.Data\TsmClient.Data.csproj" />
    <ProjectReference Include="..\..\src\TsmClient.Domain\TsmClient.Domain.csproj" />
    <ProjectReference Include="..\..\src\TsmClient.Protocol\TsmClient.Protocol.csproj" />
  </ItemGroup>
</Project>
